name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Create engine with `new EngineV10(...)`
        2. Call `RunAsync(...)` with this data
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample that reproduces the issue.
      render: csharp
      placeholder: |
        var engine = new EngineV10(100, false, false);
        engine.OnTick = async (data) => { ... };
        await engine.RunAsync(splitData);

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of Backtest.Net are you using?
      placeholder: "4.1.11"
    validations:
      required: true

  - type: input
    id: dotnet
    attributes:
      label: .NET Version
      description: Output of `dotnet --version`
      placeholder: "9.0.100"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: textarea
    id: stacktrace
    attributes:
      label: Stack Trace
      description: If applicable, paste the full exception stack trace.
      render: text

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this bug has not been reported
          required: true
        - label: I have provided all requested information
          required: true
